name: supernova_flutter
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  align_positioned: '>=3.0.0 <5.0.0'
  auto_size_text: ^3.0.0
  black_hole_flutter: ^1.1.0
  debug_overlay: ^0.2.9
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^1.0.8
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.6.4
  intl: ^0.19.0
  package_info_plus: '>=3.0.0 <8.0.0'
  platformx: ^1.1.0
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  stack_trace: ^1.10.0
  streaming_shared_preferences: ^2.0.0
  supernova:
    # path: ../supernova
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 16e713c9db21416edc8668b74dc2da111c4bf1d9
  timeago: ^3.6.0
  timeago_flutter: ^3.6.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    # https://pub.dev/packages/time_machine#flutter-specific-notes
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

  fonts:
    - family: FlatIconsFilledRounded
      fonts:
        - asset: fonts/flaticons-filled-rounded.ttf
    - family: FlatIconsOutlinedRounded
      fonts:
        - asset: fonts/flaticons-outlined-rounded.ttf
