name: supernova_flutter
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0 <3.8.0'

dependencies:
  align_positioned: ^3.0.0
  assorted_layout_widgets: ^7.0.0
  async: ^2.8.2
  auto_size_text: ^3.0.0
  black_hole_flutter: ^1.0.0
  data_size: ^0.2.0
  debug_overlay: ^0.2.3
  diacritic: ^0.1.3
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_deep_linking: ^0.2.1
  flutter_hooks: ^0.18.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.1
  flutter_math_fork: ^0.6.0
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^1.0.0
  get_it: ^7.1.3
  image_picker: ^0.8.5
  octo_image: ^1.0.0+1
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  petitparser: ^5.0.0
  platformx: ^1.1.0
  sliver_tools: ^0.2.5
  stack_trace: ^1.10.0
  streaming_shared_preferences: ^2.0.0
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 7492dd037e1f02ecedd3b3d7bac3fc1b1ce7469e
  timeago_flutter: ^1.0.0
  url_launcher: ^6.0.2

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    # https://pub.dev/packages/time_machine#flutter-specific-notes
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

  fonts:
    - family: FlatIconsFilledRounded
      fonts:
        - asset: fonts/flaticons-filled-rounded.ttf
    - family: FlatIconsOutlinedRounded
      fonts:
        - asset: fonts/flaticons-outlined-rounded.ttf
