name: supernova_flutter
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  align_positioned: ^3.0.0
  async: ^2.8.2
  auto_size_text: ^3.0.0
  black_hole_flutter: ^1.0.0
  debug_overlay: ^0.2.3
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.0.3
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_hooks: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  flutter_timezone: ^1.0.7
  get_it: ^7.1.3
  package_info_plus: ^4.0.2
  platformx: ^1.1.0
  sliver_tools: ^0.2.12
  stack_trace: ^1.10.0
  streaming_shared_preferences: ^2.0.0
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 4ff8db40ec6f6a7eceb998abe7114e628d878790
  timeago_flutter: ^3.5.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    # https://pub.dev/packages/time_machine#flutter-specific-notes
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

  fonts:
    - family: FlatIconsFilledRounded
      fonts:
        - asset: fonts/flaticons-filled-rounded.ttf
    - family: FlatIconsOutlinedRounded
      fonts:
        - asset: fonts/flaticons-outlined-rounded.ttf
