name: supernova_flutter
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  align_positioned: ^3.0.0
  async: ^2.8.2
  auto_size_text: ^3.0.0
  black_hole_flutter: ^1.0.0
  debug_overlay: ^0.2.9
  firebase_core: ^2.18.0
  firebase_crashlytics: ^3.4.1
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  flutter_timezone: ^1.0.8
  get_it: ^7.6.4
  package_info_plus: ^4.2.0
  platformx: ^1.1.0
  sliver_tools: ^0.2.12
  stack_trace: ^1.10.0
  streaming_shared_preferences: ^2.0.0
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 9f71f4585786d454530fef360c3dc7e4b4b81de7
  timeago_flutter: ^3.5.0
  url_launcher: ^6.2.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    # https://pub.dev/packages/time_machine#flutter-specific-notes
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

  fonts:
    - family: FlatIconsFilledRounded
      fonts:
        - asset: fonts/flaticons-filled-rounded.ttf
    - family: FlatIconsOutlinedRounded
      fonts:
        - asset: fonts/flaticons-outlined-rounded.ttf
