name: supernova_flutter
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

resolution: workspace
dependencies:
  align_positioned: '>=3.0.0 <6.0.0'
  auto_size_text: ^3.0.0
  black_hole_flutter: ^1.1.0
  chrono:
  debug_overlay: ^1.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get_it: '>=7.6.4 < 9.0.0'
  intl: '>=0.17.0 <0.21.0'
  package_info_plus: '>=3.0.0 <9.0.0'
  platformx: ^1.1.0
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  stack_trace: ^1.10.0
  streaming_shared_preferences: ^2.0.0
  supernova:
  timeago: ^3.6.0
  timeago_flutter: ^3.6.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^3.2.0

flutter:
  uses-material-design: true

  fonts:
    - family: FlatIconsFilledRounded
      fonts:
        - asset: fonts/flaticons-filled-rounded.ttf
    - family: FlatIconsOutlinedRounded
      fonts:
        - asset: fonts/flaticons-outlined-rounded.ttf
